#!/bin/bash

#setup NodeJS Workstation

#Create new JS entry point

touch $1.js

#Install essintial dependencies

npm init

npm i express

npm i body-parser

#setup and require libraries into JS file

echo "const express = require(\"express\");" >> $1.js

echo "const bodyParser = require(\"body-parser\");" >> $1.js

echo "" >> $1.js

echo "const app = express();" >> $1.js

echo "app.use(bodyParser.urlencoded({extended: true}));" >> $1.js

echo "app.use(express.static(\"public\"));" >> $1.js

echo "" >> $1.js

echo "//write here" >> $1.js

echo "" >> $1.js

echo "app.listen(\""$2"\", function() {" >> $1.js
echo "	console.log(\"Server is running on port "$2"\");" >> $1.js
echo "});" >> $1.js
